version: "3"
services:
  kafka:
    hostname: 'kafka'
    image: 'bitnami/kafka:2.8.1'
    ports:
      - '9093:9093'
      - '29092:29092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092 # Exposes internally - kafka:9092, and for outside world - localhost:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    depends_on:
      - zookeeper
  zookeeper:
    image: 'bitnami/zookeeper:3.9.3'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  app:
    build:
      context: .
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - .:/usr/src/app
      - ../lib:/usr/src/app/lib
    environment:
      - KAFKA_BROKERS=kafka:9092
      - AWS_ACCESS_KEY=AKKA
      - AWS_SECRET_ACCESS_KEY=KEY
      - AWS_REGION=ap-southeast-2