version: '2'

services:
  app:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    environment:
      - KAFKA_CONNECTION=kafka://kafka:9092
      - CLIENT_ID='1234-234'

networks:
  default:
    external:
      name: oaknuggins_default
